
services:
  app:
    build: .
    container_name: cpmk_app
    working_dir: /var/www/html
    user: "${APP_UID:-1000}:${APP_GID:-1000}"
    volumes:
      - ./:/var/www/html
      # - ./docker/overrides/storage/framework/views:/var/www/html/storage/framework/views
    ports:
      - "9080:9000"
    depends_on:
      - mysql
    networks:
      - cpmk

  node:
    image: node:22
    container_name: node_cpmk
    working_dir: /var/www/html
    user: "${APP_UID:-1000}:${APP_GID:-1000}"
    volumes:
      - ./:/var/www/html
    ports:
      - "5173:5173"
    networks:
      - cpmk
    command: tail -f /dev/null  # biar container node tetap hidup dan bisa exec manual

  webserver:
    image: nginx:alpine
    container_name: nginx_cpmk
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - cpmk

  mysql:
    image: mysql:8.0
    container_name: mysql_cpmk
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: e-cpmk
      MYSQL_USER: e-cpmk
      MYSQL_PASSWORD: e-cpmk
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cpmk
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_cpmk
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql_cpmk   # Sesuai nama service MySQL
      PMA_PORT: 3306
    depends_on:
      - mysql
    networks:
      - cpmk

networks:
  cpmk:

volumes:
  mysql_data: